-- Run this creation statement once after RAW ingestion.
-- Preserve all source columns and add prepared date and code columns.
CREATE TABLE AIRLINE_DB.STAGING.FLIGHTS_CLEAN AS
SELECT
    R.*,
    TRY_TO_DATE(SPLIT_PART(R.FL_DATE, ' ', 1), 'MM/DD/YYYY')
        AS FLIGHT_DATE,
    UPPER(TRIM(R.OP_UNIQUE_CARRIER)) AS CARRIER_CODE,
    UPPER(TRIM(R.ORIGIN)) AS ORIGIN_CODE,
    UPPER(TRIM(R.DEST)) AS DEST_CODE
FROM AIRLINE_DB.RAW.BTS_ONTIME_2024 AS R;

-- Validate that all RAW rows and flight dates reached STAGING.
SELECT
    COUNT(*) AS STAGING_ROWS,
    COUNT_IF(FLIGHT_DATE IS NULL) AS MISSING_FLIGHT_DATES,
    MIN(FLIGHT_DATE) AS FIRST_FLIGHT_DATE,
    MAX(FLIGHT_DATE) AS LAST_FLIGHT_DATE
FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN;

-- Show how cancellation/diversion affects arrival-delay availability.
SELECT
    CANCELLED,
    DIVERTED,
    COUNT(*) AS FLIGHTS,
    COUNT_IF(ARR_DELAY IS NULL) AS MISSING_ARR_DELAY,
    COUNT_IF(ARR_DEL15 IS NULL) AS MISSING_ARR_DEL15
FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN
GROUP BY CANCELLED, DIVERTED
ORDER BY CANCELLED, DIVERTED;

-- Measure whether standardization changed source codes.
SELECT
    COUNT_IF(OP_UNIQUE_CARRIER <> CARRIER_CODE) AS CHANGED_CARRIER_CODES,
    COUNT_IF(ORIGIN <> ORIGIN_CODE) AS CHANGED_ORIGIN_CODES,
    COUNT_IF(DEST <> DEST_CODE) AS CHANGED_DEST_CODES
FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN;
