-- Measure the number of carriers and airports represented in STAGING.
SELECT
    COUNT(DISTINCT CARRIER_CODE) AS CARRIERS,
    COUNT(DISTINCT ORIGIN_AIRPORT_ID) AS ORIGIN_AIRPORTS,
    COUNT(DISTINCT DEST_AIRPORT_ID) AS DESTINATION_AIRPORTS
FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN;


-- One row per distinct flight date in the 2024 source data.
CREATE TABLE AIRLINE_DB.ANALYTICS.DIM_DATE AS
SELECT DISTINCT
    FLIGHT_DATE AS DATE_KEY,
    YEAR(FLIGHT_DATE) AS CALENDAR_YEAR,
    QUARTER(FLIGHT_DATE) AS CALENDAR_QUARTER,
    MONTH(FLIGHT_DATE) AS MONTH_NUMBER,
    DAY(FLIGHT_DATE) AS DAY_OF_MONTH,
    DAYOFWEEKISO(FLIGHT_DATE) AS ISO_DAY_OF_WEEK,
    WEEKISO(FLIGHT_DATE) AS ISO_WEEK_NUMBER,
    YEAROFWEEKISO(FLIGHT_DATE) AS ISO_WEEK_YEAR
FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN;

-- Confirm one dimension row per date across all of 2024.
SELECT
    COUNT(*) AS DATE_ROWS,
    COUNT(DISTINCT DATE_KEY) AS UNIQUE_DATES,
    MIN(DATE_KEY) AS FIRST_DATE,
    MAX(DATE_KEY) AS LAST_DATE
FROM AIRLINE_DB.ANALYTICS.DIM_DATE;


-- Find carrier codes linked to more than one BTS airline ID.
SELECT
    CARRIER_CODE,
    COUNT(DISTINCT OP_CARRIER_AIRLINE_ID) AS AIRLINE_IDS
FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN
GROUP BY CARRIER_CODE
HAVING COUNT(DISTINCT OP_CARRIER_AIRLINE_ID) > 1;


-- Keep one row per reporting operating carrier.
CREATE TABLE AIRLINE_DB.ANALYTICS.DIM_AIRLINE AS
SELECT DISTINCT
    CARRIER_CODE,
    OP_CARRIER_AIRLINE_ID AS AIRLINE_ID
FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN;


-- Confirm one dimension row per reporting carrier code.
SELECT
    COUNT(*) AS AIRLINE_ROWS,
    COUNT(DISTINCT CARRIER_CODE) AS UNIQUE_CARRIER_CODES,
    COUNT_IF(CARRIER_CODE IS NULL OR AIRLINE_ID IS NULL) AS MISSING_KEYS
FROM AIRLINE_DB.ANALYTICS.DIM_AIRLINE;


-- Put origin and destination airport details into one temporary result.
WITH AIRPORT_RECORDS AS (
    SELECT
        ORIGIN_AIRPORT_ID AS AIRPORT_ID,
        ORIGIN AS AIRPORT_CODE,
        ORIGIN_CITY_NAME AS CITY_NAME
    FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN

    UNION ALL

    SELECT
        DEST_AIRPORT_ID AS AIRPORT_ID,
        DEST AS AIRPORT_CODE,
        DEST_CITY_NAME AS CITY_NAME
    FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN
)
SELECT
    AIRPORT_ID,
    COUNT(DISTINCT AIRPORT_CODE) AS DISTINCT_CODES,
    COUNT(DISTINCT CITY_NAME) AS DISTINCT_CITIES
FROM AIRPORT_RECORDS
GROUP BY AIRPORT_ID
HAVING COUNT(DISTINCT AIRPORT_CODE) > 1
    OR COUNT(DISTINCT CITY_NAME) > 1;


    -- Combine origin and destination airports into one dimension.
CREATE TABLE AIRLINE_DB.ANALYTICS.DIM_AIRPORT AS
SELECT
    ORIGIN_AIRPORT_ID AS AIRPORT_ID,
    ORIGIN AS AIRPORT_CODE,
    ORIGIN_CITY_NAME AS CITY_NAME
FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN

UNION

SELECT
    DEST_AIRPORT_ID AS AIRPORT_ID,
    DEST AS AIRPORT_CODE,
    DEST_CITY_NAME AS CITY_NAME
FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN;


-- Confirm one row per airport ID and check descriptive fields.
SELECT
    COUNT(*) AS AIRPORT_ROWS,
    COUNT(DISTINCT AIRPORT_ID) AS UNIQUE_AIRPORT_IDS,
    COUNT_IF(
        AIRPORT_ID IS NULL
        OR AIRPORT_CODE IS NULL
        OR CITY_NAME IS NULL
    ) AS ROWS_WITH_MISSING_DETAILS
FROM AIRLINE_DB.ANALYTICS.DIM_AIRPORT;


-- Store one row per BTS reported flight.
CREATE TABLE AIRLINE_DB.ANALYTICS.FACT_FLIGHTS AS
SELECT
    -- Keys connecting each flight to the dimensions.
    FLIGHT_DATE AS DATE_KEY,
    CARRIER_CODE,
    ORIGIN_AIRPORT_ID,
    DEST_AIRPORT_ID,

    -- Flight identity and schedule.
    OP_CARRIER_FL_NUM AS FLIGHT_NUMBER,
    TAIL_NUM AS TAIL_NUMBER,
    CRS_DEP_TIME,
    DEP_TIME,
    CRS_ARR_TIME,
    ARR_TIME,

    -- Operational measures.
    DEP_DELAY,
    ARR_DELAY,
    DEP_DEL15,
    ARR_DEL15,
    CRS_ELAPSED_TIME,
    ACTUAL_ELAPSED_TIME,
    AIR_TIME,
    DISTANCE,

    -- Disruption status and reported cause minutes.
    CANCELLED,
    CANCELLATION_CODE,
    DIVERTED,
    CARRIER_DELAY,
    WEATHER_DELAY,
    NAS_DELAY,
    SECURITY_DELAY,
    LATE_AIRCRAFT_DELAY,

    -- Only flights that operated and were not diverted qualify for arrival OTP.
    CASE
        WHEN CANCELLED = 0 AND DIVERTED = 0 THEN 1
        ELSE 0
    END AS ARRIVAL_ELIGIBLE_FLAG,

    -- Keep ineligible flights NULL rather than calling them on-time or late.
    CASE
        WHEN CANCELLED = 0 AND DIVERTED = 0 AND ARR_DELAY < 15 THEN 1
        WHEN CANCELLED = 0 AND DIVERTED = 0 THEN 0
        ELSE NULL
    END AS ARRIVAL_ON_TIME_FLAG

FROM AIRLINE_DB.STAGING.FLIGHTS_CLEAN;


-- Verify flight count and the arrival OTP flags.
SELECT
    COUNT(*) AS FACT_ROWS,
    SUM(ARRIVAL_ELIGIBLE_FLAG) AS ELIGIBLE_ARRIVALS,
    COUNT_IF(
        ARRIVAL_ELIGIBLE_FLAG = 1
        AND ARRIVAL_ON_TIME_FLAG IS NULL
    ) AS ELIGIBLE_WITHOUT_OTP_FLAG,
    COUNT_IF(
        ARRIVAL_ELIGIBLE_FLAG = 0
        AND ARRIVAL_ON_TIME_FLAG IS NOT NULL
    ) AS INELIGIBLE_WITH_OTP_FLAG,
    COUNT_IF(
        ARRIVAL_ELIGIBLE_FLAG = 1
        AND ARRIVAL_ON_TIME_FLAG <> 1 - ARR_DEL15
    ) AS BTS_FLAG_MISMATCHES
FROM AIRLINE_DB.ANALYTICS.FACT_FLIGHTS;



-- Check that every flight can link to its date, carrier, and two airports.
SELECT
    COUNT(*) AS JOINED_FLIGHTS,
    COUNT_IF(D.DATE_KEY IS NULL) AS MISSING_DATE,
    COUNT_IF(A.CARRIER_CODE IS NULL) AS MISSING_AIRLINE,
    COUNT_IF(O.AIRPORT_ID IS NULL) AS MISSING_ORIGIN,
    COUNT_IF(T.AIRPORT_ID IS NULL) AS MISSING_DESTINATION
FROM AIRLINE_DB.ANALYTICS.FACT_FLIGHTS AS F
LEFT JOIN AIRLINE_DB.ANALYTICS.DIM_DATE AS D
    ON F.DATE_KEY = D.DATE_KEY
LEFT JOIN AIRLINE_DB.ANALYTICS.DIM_AIRLINE AS A
    ON F.CARRIER_CODE = A.CARRIER_CODE
LEFT JOIN AIRLINE_DB.ANALYTICS.DIM_AIRPORT AS O
    ON F.ORIGIN_AIRPORT_ID = O.AIRPORT_ID
LEFT JOIN AIRLINE_DB.ANALYTICS.DIM_AIRPORT AS T
    ON F.DEST_AIRPORT_ID = T.AIRPORT_ID;