-- Add a consistent departure OTP rule without copying flight rows.
CREATE VIEW AIRLINE_DB.ANALYTICS.V_FLIGHT_REPORTING AS
SELECT
    F.*,

    -- Cancelled flights are excluded; diverted flights did depart.
    CASE
        WHEN F.CANCELLED = 0 THEN 1
        ELSE 0
    END AS DEPARTURE_ELIGIBLE_FLAG,

    -- Give an OTP result only to eligible departures.
    CASE
        WHEN F.CANCELLED = 0 AND F.DEP_DELAY < 15 THEN 1
        WHEN F.CANCELLED = 0 THEN 0
        ELSE NULL
    END AS DEPARTURE_ON_TIME_FLAG

FROM AIRLINE_DB.ANALYTICS.FACT_FLIGHTS AS F;


-- Check departure eligibility and compare our flag with BTS's indicator.
SELECT
    COUNT(*) AS VIEW_ROWS,
    SUM(DEPARTURE_ELIGIBLE_FLAG) AS ELIGIBLE_DEPARTURES,
    COUNT_IF(
        DEPARTURE_ELIGIBLE_FLAG = 1
        AND DEPARTURE_ON_TIME_FLAG IS NULL
    ) AS ELIGIBLE_WITHOUT_OTP_FLAG,
    COUNT_IF(
        DEPARTURE_ELIGIBLE_FLAG = 0
        AND DEPARTURE_ON_TIME_FLAG IS NOT NULL
    ) AS INELIGIBLE_WITH_OTP_FLAG,
    COUNT_IF(
        DEPARTURE_ELIGIBLE_FLAG = 1
        AND DEPARTURE_ON_TIME_FLAG <> 1 - DEP_DEL15
    ) AS BTS_FLAG_MISMATCHES
FROM AIRLINE_DB.ANALYTICS.V_FLIGHT_REPORTING;

-- Summarize flight operations at one row per calendar month.
CREATE VIEW AIRLINE_DB.ANALYTICS.V_MONTHLY_OPERATIONS AS
SELECT
    D.CALENDAR_YEAR,
    D.MONTH_NUMBER,
    COUNT(*) AS TOTAL_FLIGHTS,
    SUM(F.ARRIVAL_ELIGIBLE_FLAG) AS ELIGIBLE_ARRIVALS,
    SUM(F.ARRIVAL_ON_TIME_FLAG) AS ON_TIME_ARRIVALS,
    SUM(F.DEPARTURE_ELIGIBLE_FLAG) AS ELIGIBLE_DEPARTURES,
    SUM(F.DEPARTURE_ON_TIME_FLAG) AS ON_TIME_DEPARTURES,
    COUNT_IF(F.CANCELLED = 1) AS CANCELLED_FLIGHTS,
    COUNT_IF(F.DIVERTED = 1) AS DIVERTED_FLIGHTS
FROM AIRLINE_DB.ANALYTICS.V_FLIGHT_REPORTING AS F
JOIN AIRLINE_DB.ANALYTICS.DIM_DATE AS D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY D.CALENDAR_YEAR, D.MONTH_NUMBER;


-- Check that 12 monthly rows reconcile with the flight-level dataset.
SELECT
    COUNT(*) AS MONTHS,
    SUM(TOTAL_FLIGHTS) AS TOTAL_FLIGHTS,
    SUM(ELIGIBLE_ARRIVALS) AS ELIGIBLE_ARRIVALS,
    SUM(ELIGIBLE_DEPARTURES) AS ELIGIBLE_DEPARTURES,
    SUM(CANCELLED_FLIGHTS) AS CANCELLED_FLIGHTS,
    SUM(DIVERTED_FLIGHTS) AS DIVERTED_FLIGHTS
FROM AIRLINE_DB.ANALYTICS.V_MONTHLY_OPERATIONS;


-- Compare reporting carriers across the full 2024 dataset.
CREATE VIEW AIRLINE_DB.ANALYTICS.V_CARRIER_PERFORMANCE_2024 AS
WITH CARRIER_COUNTS AS (
    SELECT
        CARRIER_CODE,
        COUNT(*) AS TOTAL_FLIGHTS,
        SUM(ARRIVAL_ELIGIBLE_FLAG) AS ELIGIBLE_ARRIVALS,
        SUM(ARRIVAL_ON_TIME_FLAG) AS ON_TIME_ARRIVALS,
        COUNT_IF(CANCELLED = 1) AS CANCELLED_FLIGHTS
    FROM AIRLINE_DB.ANALYTICS.V_FLIGHT_REPORTING
    GROUP BY CARRIER_CODE
)
SELECT
    CARRIER_CODE,
    TOTAL_FLIGHTS,
    ELIGIBLE_ARRIVALS,
    ON_TIME_ARRIVALS,
    CANCELLED_FLIGHTS,
    ROUND(
        100.0 * ON_TIME_ARRIVALS / NULLIF(ELIGIBLE_ARRIVALS, 0),
        2
    ) AS ARRIVAL_OTP_PCT,
    DENSE_RANK() OVER (
        ORDER BY ON_TIME_ARRIVALS / NULLIF(ELIGIBLE_ARRIVALS, 0) DESC
    ) AS ARRIVAL_OTP_RANK
FROM CARRIER_COUNTS;


-- Check carrier coverage and reconcile carrier totals.
SELECT
    COUNT(*) AS CARRIERS,
    COUNT(DISTINCT CARRIER_CODE) AS UNIQUE_CARRIERS,
    SUM(TOTAL_FLIGHTS) AS TOTAL_FLIGHTS,
    SUM(ELIGIBLE_ARRIVALS) AS ELIGIBLE_ARRIVALS,
    SUM(CANCELLED_FLIGHTS) AS CANCELLED_FLIGHTS,
    MIN(ARRIVAL_OTP_RANK) AS BEST_RANK
FROM AIRLINE_DB.ANALYTICS.V_CARRIER_PERFORMANCE_2024;



-- One row per directional origin-to-destination route in 2024.
CREATE VIEW AIRLINE_DB.ANALYTICS.V_ROUTE_PERFORMANCE_2024 AS
WITH ROUTE_COUNTS AS (
    SELECT
        F.ORIGIN_AIRPORT_ID,
        O.AIRPORT_CODE AS ORIGIN_CODE,
        F.DEST_AIRPORT_ID,
        D.AIRPORT_CODE AS DEST_CODE,
        COUNT(*) AS TOTAL_FLIGHTS,
        SUM(F.ARRIVAL_ELIGIBLE_FLAG) AS ELIGIBLE_ARRIVALS,
        SUM(F.ARRIVAL_ON_TIME_FLAG) AS ON_TIME_ARRIVALS,
        COUNT_IF(F.CANCELLED = 1) AS CANCELLED_FLIGHTS
    FROM AIRLINE_DB.ANALYTICS.V_FLIGHT_REPORTING AS F
    JOIN AIRLINE_DB.ANALYTICS.DIM_AIRPORT AS O
        ON F.ORIGIN_AIRPORT_ID = O.AIRPORT_ID
    JOIN AIRLINE_DB.ANALYTICS.DIM_AIRPORT AS D
        ON F.DEST_AIRPORT_ID = D.AIRPORT_ID
    GROUP BY
        F.ORIGIN_AIRPORT_ID, O.AIRPORT_CODE,
        F.DEST_AIRPORT_ID, D.AIRPORT_CODE
)
SELECT
    *,
    ROUND(
        100.0 * ON_TIME_ARRIVALS / NULLIF(ELIGIBLE_ARRIVALS, 0),
        2
    ) AS ARRIVAL_OTP_PCT,
    RANK() OVER (ORDER BY TOTAL_FLIGHTS DESC) AS TRAFFIC_RANK
FROM ROUTE_COUNTS;

-- Confirm directional routes reconcile with the flight fact.
SELECT
    COUNT(*) AS DIRECTIONAL_ROUTES,
    SUM(TOTAL_FLIGHTS) AS TOTAL_FLIGHTS,
    SUM(ELIGIBLE_ARRIVALS) AS ELIGIBLE_ARRIVALS,
    SUM(CANCELLED_FLIGHTS) AS CANCELLED_FLIGHTS,
    MIN(TRAFFIC_RANK) AS TOP_RANK
FROM AIRLINE_DB.ANALYTICS.V_ROUTE_PERFORMANCE_2024;


-- One row per origin airport: departure performance in 2024.
CREATE VIEW AIRLINE_DB.ANALYTICS.V_ORIGIN_AIRPORT_2024 AS
SELECT
    O.AIRPORT_ID,
    O.AIRPORT_CODE,
    O.CITY_NAME,
    COUNT(*) AS REPORTED_DEPARTURES,
    SUM(F.DEPARTURE_ELIGIBLE_FLAG) AS ELIGIBLE_DEPARTURES,
    SUM(F.DEPARTURE_ON_TIME_FLAG) AS ON_TIME_DEPARTURES,
    COUNT_IF(F.CANCELLED = 1) AS CANCELLED_FLIGHTS,
    ROUND(
        100.0 * SUM(F.DEPARTURE_ON_TIME_FLAG)
        / NULLIF(SUM(F.DEPARTURE_ELIGIBLE_FLAG), 0),
        2
    ) AS DEPARTURE_OTP_PCT
FROM AIRLINE_DB.ANALYTICS.V_FLIGHT_REPORTING AS F
JOIN AIRLINE_DB.ANALYTICS.DIM_AIRPORT AS O
    ON F.ORIGIN_AIRPORT_ID = O.AIRPORT_ID
GROUP BY O.AIRPORT_ID, O.AIRPORT_CODE, O.CITY_NAME;


-- Reconcile departure counts across all origin airports.
SELECT
    COUNT(*) AS ORIGIN_AIRPORTS,
    SUM(REPORTED_DEPARTURES) AS TOTAL_FLIGHTS,
    SUM(ELIGIBLE_DEPARTURES) AS ELIGIBLE_DEPARTURES,
    SUM(CANCELLED_FLIGHTS) AS CANCELLED_FLIGHTS
FROM AIRLINE_DB.ANALYTICS.V_ORIGIN_AIRPORT_2024;


-- One row per scheduled destination airport: arrival performance in 2024.
CREATE VIEW AIRLINE_DB.ANALYTICS.V_DEST_AIRPORT_2024 AS
SELECT
    D.AIRPORT_ID,
    D.AIRPORT_CODE,
    D.CITY_NAME,
    COUNT(*) AS REPORTED_FLIGHTS_TO_DEST,
    SUM(F.ARRIVAL_ELIGIBLE_FLAG) AS ELIGIBLE_ARRIVALS,
    SUM(F.ARRIVAL_ON_TIME_FLAG) AS ON_TIME_ARRIVALS,
    COUNT_IF(F.CANCELLED = 1) AS CANCELLED_FLIGHTS,
    COUNT_IF(F.DIVERTED = 1) AS DIVERTED_FLIGHTS,
    ROUND(
        100.0 * SUM(F.ARRIVAL_ON_TIME_FLAG)
        / NULLIF(SUM(F.ARRIVAL_ELIGIBLE_FLAG), 0),
        2
    ) AS ARRIVAL_OTP_PCT
FROM AIRLINE_DB.ANALYTICS.V_FLIGHT_REPORTING AS F
JOIN AIRLINE_DB.ANALYTICS.DIM_AIRPORT AS D
    ON F.DEST_AIRPORT_ID = D.AIRPORT_ID
GROUP BY D.AIRPORT_ID, D.AIRPORT_CODE, D.CITY_NAME;


-- Reconcile flights by scheduled destination airport.
SELECT
    COUNT(*) AS DESTINATION_AIRPORTS,
    SUM(REPORTED_FLIGHTS_TO_DEST) AS TOTAL_FLIGHTS,
    SUM(ELIGIBLE_ARRIVALS) AS ELIGIBLE_ARRIVALS,
    SUM(CANCELLED_FLIGHTS) AS CANCELLED_FLIGHTS,
    SUM(DIVERTED_FLIGHTS) AS DIVERTED_FLIGHTS
FROM AIRLINE_DB.ANALYTICS.V_DEST_AIRPORT_2024;


-- Turn five BTS delay-minute columns into monthly reason categories.
CREATE VIEW AIRLINE_DB.ANALYTICS.V_DELAY_REASONS_MONTHLY AS
WITH MONTHLY_CAUSES AS (
    SELECT
        DATE_TRUNC('MONTH', DATE_KEY) AS FLIGHT_MONTH,
        COALESCE(SUM(CARRIER_DELAY), 0) AS CARRIER_MINUTES,
        COALESCE(SUM(WEATHER_DELAY), 0) AS WEATHER_MINUTES,
        COALESCE(SUM(NAS_DELAY), 0) AS NAS_MINUTES,
        COALESCE(SUM(SECURITY_DELAY), 0) AS SECURITY_MINUTES,
        COALESCE(SUM(LATE_AIRCRAFT_DELAY), 0) AS LATE_AIRCRAFT_MINUTES
    FROM AIRLINE_DB.ANALYTICS.FACT_FLIGHTS
    GROUP BY DATE_TRUNC('MONTH', DATE_KEY)
)
SELECT
    FLIGHT_MONTH,
    DELAY_REASON,
    DELAY_MINUTES
FROM MONTHLY_CAUSES
UNPIVOT (
    DELAY_MINUTES FOR DELAY_REASON IN (
        CARRIER_MINUTES,
        WEATHER_MINUTES,
        NAS_MINUTES,
        SECURITY_MINUTES,
        LATE_AIRCRAFT_MINUTES
    )
);


-- Expect five reported delay categories for each of 12 months.
SELECT
    COUNT(*) AS VIEW_ROWS,
    COUNT(DISTINCT FLIGHT_MONTH) AS MONTHS,
    COUNT(DISTINCT DELAY_REASON) AS REASONS,
    COUNT_IF(DELAY_MINUTES < 0) AS NEGATIVE_MINUTE_ROWS
FROM AIRLINE_DB.ANALYTICS.V_DELAY_REASONS_MONTHLY;



-- Confirm UNPIVOT did not add or lose reported delay minutes.
WITH FACT_TOTAL AS (
    SELECT
        COALESCE(SUM(CARRIER_DELAY), 0)
        + COALESCE(SUM(WEATHER_DELAY), 0)
        + COALESCE(SUM(NAS_DELAY), 0)
        + COALESCE(SUM(SECURITY_DELAY), 0)
        + COALESCE(SUM(LATE_AIRCRAFT_DELAY), 0)
            AS SOURCE_MINUTES
    FROM AIRLINE_DB.ANALYTICS.FACT_FLIGHTS
),
VIEW_TOTAL AS (
    SELECT SUM(DELAY_MINUTES) AS VIEW_MINUTES
    FROM AIRLINE_DB.ANALYTICS.V_DELAY_REASONS_MONTHLY
)
SELECT
    S.SOURCE_MINUTES,
    V.VIEW_MINUTES,
    S.SOURCE_MINUTES - V.VIEW_MINUTES AS DIFFERENCE
FROM FACT_TOTAL AS S
CROSS JOIN VIEW_TOTAL AS V;